// Generated by CoffeeScript 1.6.3
(function() {
  $(document).ready(function() {
    alert('blah');
    return $('#about').click(function() {
      $(this).css('text-align', 'left');
      return $('#portfolio').hide();
    });
  });

}).call(this);
