// Generated by CoffeeScript 1.6.3
(function() {
  $(document).ready(function() {
    $('#about_link').click(function() {
      $('#about_div').show();
      $('#portfolio_div').hide();
      $('#video_div').hide();
      return $('#contact_div').hide();
    });
    $('#portfolio_link').click(function() {
      $('#portfolio_div').show();
      $('#about_div').hide();
      $('#video_div').hide();
      return $('#contact_div').hide();
    });
    $('#video_link').click(function() {
      $('#video_div').show();
      $('#about_div').hide();
      $('#portfolio_div').hide();
      return $('#contact_div').hide();
    });
    return $('#contact_link').click(function() {
      $('#contact_div').show();
      $('#about_div').hide();
      $('#portfolio_div').hide();
      return $('#video_div').hide();
    });
  });

}).call(this);
